(venv) pi@pi:~/Documents/grad-proj $ python3 app.py 
Traceback (most recent call last):
  File "/home/pi/Documents/grad-proj/app.py", line 15, in <module>
    from weather.routes import weather_bp
  File "/home/pi/Documents/grad-proj/weather/__init__.py", line 7, in <module>
    from . import routes
  File "/home/pi/Documents/grad-proj/weather/routes.py", line 2, in <module>
    from .controllers import get_latest_weather_data, update_weather_data
  File "/home/pi/Documents/grad-proj/weather/controllers.py", line 7, in <module>
    from hardware.sensor_controller import SensorController
  File "/home/pi/Documents/grad-proj/hardware/__init__.py", line 6, in <module>
    from .relay import Relay
  File "/home/pi/Documents/grad-proj/hardware/relay.py", line 3, in <module>
    from shared.config import get_config
ImportError: cannot import name 'get_config' from 'shared.config' (/home/pi/Documents/grad-proj/shared/config.py)
(venv) pi@pi:~/Documents/grad-proj $ 
